    <div class="nav">
        <div class="center clear">
            <div class="nav-left">
                <div class="glitch-effect">
                    <h1 class="ge-text" aria-title="BUKEL">BUKEL</h1>
                </div>
                <ul class="fr">
                    <li class="fl">
                        <a href="/index.shtml" target="_blank" title="首页">
                            <em>首页</em>
                            <span>HOME</span>
                        </a>
                    </li>
                    <li class="fl">
                        <a href="javascript:;" target="_blank" title="精美壁纸">
                            <em>精美壁纸</em>
                            <span>WALLPAPER</span>
                        </a>
                    </li>
                    <li class="fl">
                        <a href="javascript:;" target="_blank" title="影视分享">
                            <em>影视分享</em>
                            <span>VIDEO</span>
                        </a>
                    </li>
                    <li class="fl">
                        <a href="javascript:;" target="_blank" title="编程进阶">
                            <em>编程进阶</em>
                            <span>PROGRAM</span>
                        </a>
                    </li>
                    <li class="fl cdk">
                        <a href="javascript:;" target="_blank" title="工具应用">
                            <em>应用工具</em>
                            <span>TOOL</span>
                        </a>
                    </li>
                    <li class="fl">
                        <a href="javascript:;" target="_blank" title="博客">
                            <em>博客</em>
                            <span>BLOG</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="nav-right">
                <a href="javascript:;" target="_blank" title="联系我">
                    <em>联系我</em>
                    <span class="channell">RELATION</span>
                </a>
            </div>
        </div>
        <div class="sub-nav">
            <ul class="sub-nav-inner">
                <li class="down-nav">
                    <a href="/index.shtml" target="_blank" title="首页">首页</a>
                </li>
                <li class="down-nav">
                    <!-- <a href="javascript:;" target="_blank" title="最新推荐">最新推荐</a> -->
                    <a href="list.html?type=0" target="_blank" title="原画壁纸">原画壁纸</a>
                    <a href="list.html?type=3" target="_blank" title="视频壁纸">视频壁纸</a>
                </li>
                <li class="down-nav">
                    <!-- <a href="javascript:;" target="_blank" title="最新推荐">最新推荐</a> -->
                    <a href="list.html?type=2" target="_blank" title="动漫分享">动漫专辑</a>
                    <a href="list.html?type=1" target="_blank" title="音乐">音乐专辑</a>
                </li>
                <li class="down-nav">
                    <a href="javascript:;" target="_blank" title="前端特效">前端特效</a>
                    <a href="dwang/resource.html" target="_blank" title="资源">最新资源</a>
                    <!-- <a href="/web201906/strategy.shtml?type=2" target="_blank" title="0"></a>
                    <a href="/web201906/strategy.shtml?type=3" target="_blank" title="0">0</a> -->
                </li>
                <li class="down-nav">
                    <a href="javascript:;" target="_blank" title="工具应用">工具应用</a>
                </li>
                <li class="down-nav">
                    <a href="javascript:;" target="_blank" title="SPA博客">SPA博客</a>
                    <!-- 
                     公告
                     最新
                     热门
                     排行
                     更多
                     -->
                </li>
            </ul>
        </div>
        <div class="official-channel-warp">
            <div class="official-channel">
                <ul class="channel-left fl">
                    <li class="h-wb" title="微博"><a href="//weibo.com/6092381861/profile" class="hd"
                            target="_blank"><img src="images/wb.png" width="64" height="64" class="wb">微博</a></li>
                    <li class="h-wx" title="微信">
                        <div class="hd"><img src="images/wx.png" width="64" height="64" class="wx">微信</div>
                    </li>
                    <li class="h-bl" title="QQ"><a href="javascript:;" class="hd" target="_blank"><img
                                src="images/qq.jpg" width="64" height="64" class="xqbl">QQ</a></li>
                </ul>
                <ul class="channel-right fl">
                    <li class="odd">302072920（QQ群）</li>
                    <li class="odd">进群暗号：bukeL </li>
                </ul>
            </div>
        </div>
    </div>